// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d887aa7e-9622-4820-8a59-48fca13362f8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_kYZgInN9U",
    "aws_user_pools_web_client_id": "26kf6irq8s20p15ulaf38jp032",
    "aws_content_delivery_bucket": "admin.feedmytrip.com",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://admin.feedmytrip.com.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
